config/routes.rb
WeightRecorderP130330::Application.routes.draw do

  resources :records

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "records#index"
  resources :users
  resources :sessions

  resources :records

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  attr_accessible :memo, :weight#, :user_id#, :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :records

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
# coding = utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authorize

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to log_in_url, notice: "ログインして下さい"
    end
  end
end
# TODO usersコントローラを作る
# TODO userモデルを作る
# TODO usersコントローラを実装する
# TODO users/newビューを実装する
# TODO routeを編集する
# TODO userモデルを編集する
# TODO sessionコントローラを作る
# TODO sessions/newビューを実装する
# TODO routeを編集する
# TODO sessionコントローラを実装する
# TODO userモデルを編集する
# TODO applicationビューを編集する
# TODO routeを編集する
# TODO sessionコントローラを編集する
# TODO リンクを追加する
# TODO ヘルパーメソッドを追加する
# TODO userモデルを編集する
# TODO 閲覧画面を作る
# TODO 非ログイン者に対する閲覧制限をかける

# TODO 時間があれば画面遷移などを改良する

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    # 新規レコード
    @record = Record.new

    # テーブルのソート
    sort_column = params[:sort_column].nil? ? 'created_at' : params[:sort_column]
    if sort_column == 'created_at'
      @records = Record.order(sort_column + ' DESC')
    else
      @records = Record.order(sort_column + ' DESC, created_at DESC')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    #@record = Record.new(user: current_user)
    #@record = current_user.records.new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    #@record = Record.new(params[:record])
    @record = current_user.records.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to records_url, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to records_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to log_in_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeightRecorderP130330</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
      Logged in as <%= current_user.email %>
      <%= link_to "Log out", log_out_path %>
  <% else %>
      <%= link_to "Sign up", sign_up_path %> or
      <%= link_to "Log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%#= f.label 'user id' %><br />
    <%#= f.text_field :user_id %>
  </div>-->
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight, size: 10%> kg
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo, size: "20x2" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<%#= link_to 'New Record', new_record_path %>

<%= render 'form' %>

<br />

<table>
  <tr>
    <th><%= link_to "Date", records_url(sort_column: "created_at") %></th>
    <th><%= link_to "Weight", records_url(sort_column: "weight") %></th>
    <th><%= link_to "Email", records_url(sort_column: "user_id") %></th>
    <th>Memo</th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.created_at.strftime('%m月%d日 %H時') %></td>
    <td><%= record.weight %> kg</td>
    <!-- email@domain を email に置換する-->
    <td><%= record.user.email.gsub(/(?<username>.+)\@.*/, '\k<username>') %></td>
    <td><%= record.memo %></td>
    <td><%= link_to 'Edit', edit_record_path(record) %></td>
    <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p>
  <b>Email:</b>
  <%= @record.user.email %>
</p>

<p>
  <b>Weight:</b>
  <%= @record.weight %>
</p>

<p>
  <b>Memo:</b>
  <%= @record.memo %>
</p>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any?%>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>